In [1]:
import numpy as np

In [9]:
a = np.random.rand(2,3)

In [15]:
type(a)

numpy.ndarray

In [16]:
b = a.shape[0]

In [17]:
b

2

In [18]:
a

array([[0.95629064, 0.28352947, 0.13256456],
       [0.43382533, 0.45421989, 0.37529974]])

In [21]:
c = a.reshape((-1,1))
c

array([[0.95629064],
       [0.28352947],
       [0.13256456],
       [0.43382533],
       [0.45421989],
       [0.37529974]])

In [23]:
a.T

array([[0.95629064, 0.43382533],
       [0.28352947, 0.45421989],
       [0.13256456, 0.37529974]])